### ISSUE TITLE
Doubt regarding usage

### ISSUE THREAD

**Issue by akshitac8** [waldeland/CNN-for-ASI#11]
Hello Dr Waldeland,

I have been trying to work through your code on Penobscot interpretation dataset for facies classification. I had a few questions:
1. I need to work with multi-label classification. So, I need to store a single image in train folder with all the classes drawn in that image or I need to store separate image files.
Thank you in advance :slightly_smiling_face:

**Comment by waldeland** [comment]
Hi, that should be no problem. Just use different colors for each class and update the color_table in data.py accordingly.

**Comment by waldeland** [comment]
https://github.com/waldeland/CNN-for-ASI/blob/b497ce17c1ee0f0499eba459eba85e263ca522c3/data.py#L131
