### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by farzanullah** [waldeland/CNN-for-ASI#14]
Dear Mr. Waldeland,

I would like to express extreme gratitude for your services in this field.

Can you please tell how to visualize a particular cross line or inline as you have done in your paper?

Your help in this matter would be highly appreciated.

Regards,
Mohammad Farzanullah

**Comment by waldeland** [comment]
Hi, when you have the output cube, you can just select the desired inline
and use a suited plotting library.

Best regards
Anders

ons. 12. jun. 2019 kl. 08:48 skrev farzanullah <notifications@github.com>:
