### ISSUE TITLE
Extract cross/inlines from SEG-Y as images

### ISSUE THREAD

**Issue by KirillSimonov** [waldeland/CNN-for-ASI#17]
Dear Mr. Anders Waldeland,

Thank you for sharing your work! I am new to using ML and DL for Seismic Interpretation. I want to try your workflow out. 
Could you please explain how you managed to extract cross/inlines in form of grayscale images from SEG-Y file?
I donwloaded Penobscot dataset with all cross/inlines and masks, and want to manage my SEG-Y file in the same manner.
I have my dataset from Petrel; there is no such option. I searched the web and have not found solution.
Thank you.

---
Sincerely,
Kirill

**Comment by waldeland** [comment]
I recommend the segyio-package to read segues with python. From there you can save them as images with i.e. matplotlib or scipy.
