### ISSUE TITLE
License and article

### ISSUE THREAD

**Issue by LukasMosser** [waldeland/CNN-for-ASI#2]
Thank you for sharing your code!

I saw that this is missing a license, if you could please add one, otherwise it is difficult to contribute and build on top of.

Second question: When will the article be released?

Thanks!

**Comment by waldeland** [comment]
Hi and thank you for your interest!

License: Im not to familiar with how I am supposed to publish the license, but there is a file called LICENSE in the repository. Is this enough?

Article: Most likely sometime mid-2018.

**Comment by LukasMosser** [comment]
Perfect. 

Thanks! Looking forward to reading your article.

**Comment by waldeland** [comment]
Paper is out now:
https://library.seg.org/doi/abs/10.1190/tle37070529.1
