### ISSUE TITLE
Exception during training with 3 classes

### ISSUE THREAD

**Issue by ghost** [waldeland/CNN-for-ASI#7]
We tried to use the code to train a network to identify 3 classes.

To do this using our own image data we modified the `class_color_coding` dict in `data.py` to be
```
# Add colors to this table to make it possible to have more classes
class_color_coding =[
    [0,0,232], #non-gully
    [250,170,30], #gullies
    [207,207,207], #undefined
] 
```

after doing this the network would not train successfully and an exception occurs. On debugging it appears that the code tries to locate non existent labels with a `class_ind > 2`

**Comment by Jessaminzyx** [comment]
Hi, professor,sorry to bother you . I am the new to the CNN ,I have a question about how to make the label which is only a slice? And if  we divide colors according to set thresholds.

**Comment by waldeland** [comment]
Thanks for the update. I have done a few tests now, and it seems to be working. (@Jessaminzyx, please send me an email, and I will try to do my best to help you.)
